### ISSUE TITLE
Minified Version of SDK No Where to be found

### ISSUE THREAD

**Issue by NicolasPerl** [steemit/steemconnect-sdk#43]
Clicking on the link [https://steemit.github.io/sc2-angular/sc2.min.js](url) brings up an error page. 

Is there somewhere else I can find the minified SDK for steemconnect?

**Comment by bonustrack** [comment]
You can get it here: https://github.com/steemit/example-steemconnect-angular/blob/master/sc2.min.js or build it from this repo.

**Comment by NicolasPerl** [comment]
You're great - thanks so much for the prompt response.
